env:
  global:
    - secure: "wxSBlXcC1xVuqJpPyYLtRMyQ+8gVg4WOYBNYMmiXLUVJZPQfdGJY+2RTkDs0XsU69Fje5F6U1iyBdz+zHd0NKh/LaO8GFPzwcKiwZNlyaTuelvQQ66N4xprlG3xbUR8rU/ExRqTGNKij3IFy6JWi/ETMGq0UFl6jcOsE7FufFcEJaP5KN7Jf162rBdHWi7UcQ3NViSWyjgjVYt5nD92ktFI9wqc/sD1pRfcLAYqESL0MotkQFnVmdlHMYrxcWechyRm6feRfqIIsHqESp0Jv8L0IaBKbLy4xQMauDdEk1aPuHEK6Po8WxuEjOHsKVBt+JHziSDn/O7vj6zQtQZ8mivnTmqGnlqxnj7SBE6GExnuAfBtFiT7aNruguJwTfhkp0ZlrJX4tObxGBDTvTA6H+IOXC4PnzFikf0ms6hvezx3dxfiVyRfPhsdRdVYJWn7EaDMfsTiiu1ZrSxLF/y512z1XO0ZQ9Ykj0di8uULD4Sj9P7gLsdCe495bQbRmu9DTDz4k//ijBwq8SJD5RUNc571opyrYAqrVV7SQgHSfm3M9l7VTTPlidxKf3AgGVKntZvp4jTjOKEYwaUZIzLJ0EFlW7OuF1LWRIBYmuMgBrwKAxjXDHclT2hAZqnvGLg+CKNTnAlUGIMzaEBKL3O0Kf/u/x2H0quW2aciplutOC0c="
    - secure: "N5L2SD6BbzP8hEuR3585QQ4c6hsA91wHF/ltt/FeVXDbqhCikA0jLYunvVNKNXlO4Cuh8SZCorj5BuPloYzScXucIgomsfXm4TQBkQ03mmt+9EnmoJ3U6DbFADbl4TRw2mV93eG+/rxdP+hYk75V4hfozwOXLxGWLhfIcmKoiiFJ19DxqksWH7RoE3yMVbh4GmUIuf/2bp4wv60QZdyG1gD4x67VzS0TUr1IOOn1cJULoMorMvenhCgCkHqD8Ntb8GcDL08Fbe24eb+tOKCUYHPaT3orPPERR401LSLg5LYRFfNm+Ibwbgnt9yqzRC0mfJYVmypO7/VXoyXTBWKqfP0hQYMXHcTKjoI2HJxygBtEtcd+cBwMhKnI4M4QdBcs+TTmCIsG5q+p3ow3RkIiNhUDSA3xOTBZ5uQJHyxKCBgKkuN+G3Sm+S/2w5MSteLcCvmeoyDtVZA7AXmku/aBbL+WlKy+n/wcLSj5ZQqldK5+nLMTfxjOS3BVnZtlGg2IXvKvjAShH+tjkwkKmoLBaR1nI4Qf/X2t1yP3oo+F156/kNVJM02MIQYh2KNilNEC2SsG0iTmYYo2e20PhjvUvfXMCSkWgzoXPsGgWaHZf3C1mhfTwgQD0ay+tFo87V4m6Wskm8j/BBxmQXrPyXujaisvjW0YHccXTsHOU8One54="

language: minimal

git:
  depth: false

script: true

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: master
