env:
  global:
    - secure: "u2QBNqrQRtKuHNt1UeraOdq0Iyx0/rTKrnihJTYT4Anqy2hlIgEapbsoZVo64la+D3X8AGRZ5h5ZH8SWvHXHGbrBuhshVoWxg1RL17DzF9wjOJvJxmaz434dwnwsPgr86ngfQFdjX/9T4zGGsepCl3J6K7QzE7bMBuyhG3/ZbAffQvY6jNPGE85IFV+f94NQxicii29318aDwx/rvGC0MGl5p+9s3dR7VnvwUICUF8ajp0ReNV6uT/T1sRPvnmqg4oVk0isYZdUo/5bZ1CJiamV34UdVS+Bz8oWA4XJDQ3T4peHrQ1c16B2Tur769SL2+6lok41PjM1v5dGfwxnhYhSxtFVPiBf83E9+WjCcBoowP+8vHift+y/WTAzwC8C6LbNhrJRw9Xqd9NGBR0fUmVOVvMofcIWswdVyx8cXQbOJgL8hoSk5dJl9obz1ESMBwaVeIFSkmMSLE0Hwr1+8q268d0AR6BHseRtzDwKPYtuMzJ4WtDqBJVY4Fwz5TWA/TQa4yHCdFIbldpXpcqamlLK1jcJrj4bQUqX34rkeWk6PLc6SH1VquCHV7zgmvjZ7u8Kd7K+4zYOEqcEBnb8sWESTJdMTXEPfO+sbZIOi278GL6tepQXzkd6xWZQGuZYuppSTNtTfwJA7fo8N4HBtQdbo1166e4O/kLv9+lhI61Q="
    - secure: "kv3ltRG+DWwwFjyUhwDY8VwG0cGMfnfAryWg6hIV/dAYjnK4swOu0NEvnk897zqNA68ekjbk/pqi6vVmO88pYIcfMZCUd4vowYD4NH1fIsJIuJwA7sxuIFymM2BwlBunFG5z9yyCCqy8ZIcIzVW1NltNDq3nswzF76o/EdhaeyK+iQT1UMcFfqifqvJY/LwJ2naFMgGrhVIgw7n4jhwg9JHJXtN7HlNo4nBH7pGYA5eNCzCaHkXV9/rRSlDxN6sGcwmbcN+SggU3NH7OMQIrZFEeWWkXr+TGHTgGVjAXjibkCzL1Lfkll7SONYs6ZiQ2pYhxsH0eVYUcUS6VxennsIAQcj4LF/p3g2+VKFTYem7/D77eC7ubuo1cDCeu2ny+Ae1xl2fU3M15JD35+j1JMSbr7Q4Bk619jzaNzy3K+f8XZYtFwRNv7ftwFqCprDqnxq9RPx7fRU6YJwJRD8haDmozIN9i3dBzsHABpGv+mH5x9+tQK6aa272BwumPGOA8IqEpC8t68roQfLljOG5IzpyZNrvIAIoUprK2TwcSeA2YqNB9hv1hySnci1jyHfnNJh/4/b5+drvkl4qiauVOhWlFxVTfjw4kpgvUaKtY+aNGPgqNNbalKX8UFt52UZ8ncOLG2GzhtyGa65P1r6tFsdvSkt7czyw7q0z3psTX6MY="

language: minimal

git:
  depth: false

script: true

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: master
